// docs/site.md sections 7.1 and 19. The only site-coded strings; everything
// else a visitor reads comes from the content document.

export const copy = {
  loading: {
    initial: "Loading",
    slow: "Still trying to reach the server",
  },
  reload: {
    body: "The site needs to reload to get the latest updates.",
    button: "Reload",
  },
  banners: {
    updatesPaused: "Updates paused, retrying",
    offline: "You appear to be offline",
    preview: "Preview",
    previewLive: (time: string) => `Live, last change ${time}`,
    previewReconnecting: "Reconnecting",
    previewExpired: "This preview link has expired",
    previewExit: "Exit preview",
    previewRetry: "Retry",
  },
  notFound: {
    heading: "Page not found",
    home: "Back to home",
  },
  signIn: {
    hint: "Sign in to continue",
    button: "Sign in",
    signOut: "Sign out",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    unreachable: "Could not reach the server.",
    misconfigured: (variable: string) =>
      `Site misconfigured: ${variable} is missing or malformed.`,
  },
  live: {
    live: "Live",
    updating: "Polling",

    offline: "Offline",
    updatedAgo: (seconds: number) => `Updated ${seconds}s ago`,
    watchingSuffix: " watching",
    waitingForFix: "Waiting for the first fix",
    signalLostAgo: (seconds: number) => `No update for ${seconds}s`,
    unavailablePlaceholder: "N/A",
  },
  map: {
    unavailable: "Map unavailable",
    retry: "Retry",
    trackerMenu: "Tracker menu",
    messages: {
      label: "Latest message",
      labelUnread: "Latest message, new",
      title: "Flight updates",
      newMarker: "New",
      close: "Close",
    },
    flightDock: {
      title: "Flight data",
      speed: "Speed",
      altitude: "Altitude",
      heading: "Heading",
      airborne: "Airborne",
      distance: "Distance",
      accuracy: "Accuracy",
    },
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    centerOnSanta: "Center on Santa",
    snow: "Snow",
    routeStart: "Starts here",
    routeMap: {
      region: "Santa's planned route; the star marks where he starts",
      fullscreen: "Show the route map fullscreen",
      exitFullscreen: "Exit fullscreen",
      terrain: "Terrain view",
      landmark: (name: string) => `About ${name}`,
      closeLandmark: "Close",
      directions: "Get directions",
    },
  },
  tracker: {
    data: "Data",
    location: "Location",
    history: "History",
    times: "Times",
    landmarks: "Landmarks",
    close: "Close",
  },
  sponsors: {
    open: "Sponsor",
    previous: "Previous sponsor",
    next: "Next sponsor",
    website: "Website",
    facebook: "Facebook",
    instagram: "Instagram",
    close: "Close",
  },
  cookies: {
    leave: "Leave cookies",
    signInToLeave: "Sign in to leave a cookie",
    title: "Leave cookies for Santa",
    remaining: (remaining: number, limit: number) => `${remaining} of ${limit} left`,
    more: (name: string) => `One more ${name}`,
    fewer: (name: string) => `One fewer ${name}`,
    noteLabel: "Note (optional)",
    noteInvalid: "Please check your note.",
    submit: (n: number) => (n === 1 ? "Leave 1 cookie" : `Leave ${n} cookies`),
    onlyLeft: (n: number) => (n === 1 ? "You only have 1 cookie left. Please pick again." : `You only have ${n} cookies left. Please pick again.`),
    thanks: (n: number) => (n === 1 ? "Thanks for the cookie." : `Thanks for the ${n} cookies.`),
    limitReached: "You have left all your cookies for this year",
    typeGone: "That cookie type is no longer active. Please pick another.",
    tooMany: (secs: number) => `Too many requests. Try again in ${secs}s.`,
    wait: (secs: number) => `Wait ${secs}s`,
    cancel: "Cancel",
    close: "Close",
  },
  theme: {
    picker: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  nav: {
    more: "More",
  },
  alerts: {
    bell: "Alerts",
    bellNew: (n: number) => `Alerts, ${n} new`,
    badge: (n: number) => (n > 9 ? "9+" : String(n)),
    title: "Your alerts",
    empty: "No alerts have been sent to you yet",
    newMarker: "New",
    kindStatus: "status",
    kindUpdate: "update",
    close: "Close",
  },
  auth: {
    signIn: {
      title: "Sign in",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      links: {
        signUp: "Create account",
        forgot: "Forgot password",
        home: "Home",
      },
      wrongCredentials: "Wrong email or password",
      needsConfirming: "Your account needs confirming",
    },
    signUp: {
      title: "Create account",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      submit: "Create account",
      links: {
        signIn: "Sign in",
        home: "Home",
      },
      alreadyExists: "That email already has an account",
      alreadyExistsSignIn: "Sign in",
      invalidEmail: "Please enter a valid email address",
      passwordTooShort: "Password must be at least 12 characters",
      passwordsDoNotMatch: "Passwords do not match",
      invalidPassword: "Password must be at least 12 characters",
    },
    confirm: {
      title: "Confirm your account",
      hint: "We emailed you a code.",
      code: "Confirmation code",
      submit: "Confirm",
      resend: "Resend code",
      resendWait: (secs: number) => `Resend in ${secs}s`,
      confirmed: "Account confirmed",
      signInAfter: "Sign in",
      codeBad: "Please check the code",
      codeExpired: "That code has expired. Send a new one.",
      links: {
        signIn: "Sign in",
        home: "Home",
      },
    },
    forgot: {
      title: "Forgot password",
      email: "Email",
      submit: "Send code",
      emailed: "We emailed you a code.",
      links: {
        signIn: "Sign in",
        signUp: "Create account",
        home: "Home",
      },
    },
    reset: {
      title: "Reset password",
      code: "Confirmation code",
      password: "New password",
      confirmPassword: "Confirm password",
      submit: "Set password",
      changed: "Password changed",
      signInAfter: "Sign in",
      codeBad: "Please check the code",
      codeExpired: "That code has expired.",
      links: {
        signIn: "Sign in",
        home: "Home",
      },
    },
    errors: {
      tooMany: "Too many attempts, wait a minute",
      generic: "Something went wrong. Please try again.",
    },
  },
} as const;
